import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ScheduleCData, TaxProfile } from '../types';
import { formatCurrency } from './financeService';

// Extend jsPDF type to include autotable
// Removed interface, using any for doc to avoid type issues

export const generateTaxPDF = (
  data: ScheduleCData, 
  profile: TaxProfile, 
  year: number,
  isDraft: boolean = true
) => {
  const doc: any = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;

  // --- Watermark ---
  if (isDraft) {
    doc.setTextColor(230, 230, 230);
    doc.setFontSize(60);
    doc.setFont('helvetica', 'bold');
    doc.text('DRAFT DO NOT FILE', pageWidth / 2, doc.internal.pageSize.height / 2, {
      align: 'center',
      angle: 45,
    });
  }

  // --- Header (Form 1040 Style) ---
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('SCHEDULE C', margin, 20);
  
  doc.setFontSize(10);
  doc.text('(Form 1040)', margin, 25);
  doc.setFont('helvetica', 'normal');
  doc.text('Profit or Loss From Business', margin + 60, 20);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(year.toString(), pageWidth - margin - 20, 20);

  // --- Entity Info Box ---
  doc.setLineWidth(0.5);
  doc.line(margin, 30, pageWidth - margin, 30);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name of proprietor: ${profile.entityType === 'SOLE_PROP' ? 'Sole Proprietor' : profile.entityType}`, margin, 36);
  doc.text(`SSN/EIN: ${profile.taxId}`, pageWidth - margin - 50, 36);
  
  doc.text(`Address: ${profile.address}, ${profile.city}, ${profile.state} ${profile.zip}`, margin, 42);
  doc.text(`Accounting Method: Cash`, pageWidth - margin - 50, 42);

  doc.line(margin, 46, pageWidth - margin, 46);

  // --- Part I: Income ---
  doc.setFont('helvetica', 'bold');
  doc.text('Part I   Income', margin, 54);
  
  autoTable(doc, {
    startY: 58,
    head: [['Line', 'Description', 'Amount']],
    body: [
      ['1', 'Gross receipts or sales', formatCurrency(data.grossReceipts)],
      ['2', 'Returns and allowances', '$0.00'],
      ['3', 'Subtract line 2 from line 1', formatCurrency(data.grossReceipts)],
      ['4', 'Cost of goods sold (from Part III)', formatCurrency(data.costOfGoodsSold)],
      ['5', 'Gross profit. Subtract line 4 from line 3', formatCurrency(data.grossProfit)],
      ['7', 'Gross income', formatCurrency(data.grossProfit)],
    ],
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: 'bold', width: 15 },
      2: { halign: 'right', font: 'courier' }
    },
  });

  // --- Part II: Expenses ---
  const finalYPart1 = doc.lastAutoTable.finalY + 10;
  doc.setFont('helvetica', 'bold');
  doc.text('Part II   Expenses', margin, finalYPart1 - 2);

  // Convert expenses object to array
  const expenseRows = Object.entries(data.expenses).map(([key, val], index) => {
    // Strip "Part II Line X:" prefix for cleaner PDF
    const cleanName = key.includes(':') ? key.split(':')[1].trim() : key;
    return [(index + 8).toString(), cleanName, formatCurrency(val as number)];
  });

  // Add Totals
  const totalExp = Object.values(data.expenses).reduce((a, b) => a + (b as number), 0);
  expenseRows.push(['28', 'Total expenses', formatCurrency(totalExp)]);

  autoTable(doc, {
    startY: finalYPart1 + 2,
    head: [['Line', 'Description', 'Amount']],
    body: expenseRows,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: 'bold', width: 15 },
      2: { halign: 'right', font: 'courier' }
    },
  });

  // --- Summary & Signature ---
  const finalYPart2 = doc.lastAutoTable.finalY + 10;
  
  // Net Profit Box
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, finalYPart2, pageWidth - (margin * 2), 20, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('31. Net profit or (loss)', margin + 5, finalYPart2 + 13);
  doc.setFont('courier', 'bold');
  doc.text(formatCurrency(data.netProfit), pageWidth - margin - 5, finalYPart2 + 13, { align: 'right' });

  // Digital Signature Block
  const sigY = finalYPart2 + 35;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.line(margin, sigY, pageWidth / 2, sigY);
  doc.text('Sign Here', margin, sigY + 5);
  
  doc.line(pageWidth / 2 + 10, sigY, pageWidth - margin, sigY);
  doc.text('Date', pageWidth / 2 + 10, sigY + 5);

  if (!isDraft) {
    doc.setFont('times', 'italic');
    doc.text(`Digitally Generated by Lansky Ledger`, margin + 5, sigY - 2);
    doc.text(new Date().toLocaleDateString(), pageWidth / 2 + 15, sigY - 2);
    
    // UUID for Audit Trail
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(`Audit ID: ${crypto.randomUUID()}`, margin, doc.internal.pageSize.height - 10);
  }

  // Disclaimer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text('This is a facsimile for record-keeping. Consult a tax professional for official filing.', margin, doc.internal.pageSize.height - 20);

  doc.save(`Lansky_Tax_Worksheet_${year}_${isDraft ? 'DRAFT' : 'FINAL'}.pdf`);
};